config/routes.rb
Rails.application.routes.draw do
  get 'welcome/:first_name', to: 'welcome#show'
  get 'profil/:user', to: 'profil#show'
  get 'gossip/:id', to: 'gossip#show'
  get '/', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'

  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :gossips_tags
  has_many :tags, through: :gossips_tags
end

app/models/gossip_table.rb
class GossipTable < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips_tags
  has_many :gossips, through: :gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  	@user = User.find(@gossip.user_id)
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def show
    @user = User.find(params[:user])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

  def home
    @gossip_array = Gossip.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  attr_accessor :first_name

  def show
    @user = User.create(first_name: params[:first_name])
    @gossip_array = Gossip.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/show.html.erb
<div class="card">
  <div class="card-header">
    <%=@gossip.title%>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%=@gossip.content%></p>
      <footer class="blockquote-footer">Ecrit par <%=@user.first_name%>  le  <%=@gossip.created_at%> <br>
      <a href ='/profil/<%=@user.id%>'>Voir le profil de l'auteur</a></footer>
    </blockquote>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" href="/welcome/:first_name">Accueil</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Team", team_path %> </a>
        </li>
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Contact", contact_path %> </a>
        </li>
      </ul>
    </div>
  </nav>

    </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profil/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Profil de <%=@user.first_name%> <%=@user.last_name%></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%=@user.email%> | <%=@user.age%> ans | from <%=City.find(@user.city_id).name%></h6>
    <p class="card-text"><%=@user.description%></p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<h1>Contactez nous !</h1>
<p>Contactez Guillemette</p>
<p>Contactez Valentin</p>

app/views/static_pages/team.html.erb
<h1>Voici notre équipe lol mdr 😇❤️😻</h1>
<p>Guillemette </p>
<p>Valentin </p>

app/views/welcome/show.html.erb
<h1>Welcome <%= @user.first_name%> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>

<div class="card-columns">
<% @gossip_array.each do |gossip| %>
  <div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header"><%= User.find(gossip.user_id).first_name %></div>
    <div class="card-body text-dark">
      <h5 class="card-title"><%= gossip.title %></h5>
      <p class="card-text"><a href ='/gossip/<%=gossip.id%>'>Voir plus...</a></p>
    </div>
  </div>
<% end %>
</div>